FROM python:3.9.10

WORKDIR /app

COPY main.py app.py config.py models.py routers.py utils.py tests.py requirements.txt ./

RUN python -m pip install --upgrade pip

RUN python -m pip install -r requirements.txt

CMD [ "python", "main.py" ]